---
title: "Overview"
---

Dynamically visualize data from [Data Axle](https://doc.arcgis.com/en/esri-demographics/latest/arcgis-places/data-axle.htm) to display four metrics related to church closures at the tract level over various date ranges. Include 'snapshot' views of socioeconomic information about the areas alongside the church closure metrics.

## Project Goals

Findings addressing each of these objectives are accessible via the navigation bar in the top right.

1. **REVIEW:** Evaluate the raw data and previously outlined cleaning, validation, and harmonization methods employed by [Dr. Insang Song](https://sigmafelix.wixsite.com/mysite) for accuracy and identify opportunities for improvement.

2. **PREPARATION:** Implement identified improvements to prepare the dataset for analysis and distribution to qualifying collaborators.

3. **METRICS:** Calculate the metrics necessary for dynamic visualization.

## Important Links and Locations

In accordance with the Data Use Agreement for this dataset, some repositories may not be publicly accessible or may contain local files that are not tracked by Git and or included on GitHub. Complete copies of the data and summary results can be accessed in the 'SOCAH LAB\\Church closing\\Raw data' folder on Yale's OneDrive.

Active dashboard prototype: [Closed Churches in the US](https://church-closing-dashboard.vercel.app/)

Original GitHub Repo by Dr. Song: [sigmafelix/healthreligion_project](https://github.com/sigmafelix/healthreligion_project)

Current Project GitHub Repo by Shelby: [SOCAH-Lab/Church-Closures-Dashboard](https://github.com/SOCAH-Lab/Church-Closures-Dashboard)

## Repository Note

The Data Use Agreements (DUAs) with the data owner, Data Axle, prohibit public distribution of the raw data. Accordingly, individual-level files are stored in `~/KEEP LOCAL` directories. While most local-only files are individual-level data, some code or results may also be restricted.

All publicly distributed results are summarized, and all publicly distributed code has been constructed to avoid directly revealing or referencing individual-level results. Executing all code below requires access to the raw data and results.

API keys are user-specific and are not publicly distributed. Where applicable, instructions have been provided to help users obtain their own API keys.

## 2023 vs. 2026 Format

In May 2026, an updated version of the raw data was provided in a different format than the version exported in July 2023 and provided in the summer of 2025. As a result, data processing was split into two paths: one for the 2023 format and one for the 2026 format.

The 2026 versions of comparable sections should be treated as the most current method applicable for ongoing research. Insights from the 2023 format are assumed to apply to the 2026 format as well. Unexpected outcomes or shortcomings in algorithm performance identified in the 2023 drafts were used to inform improvements applied in the 2026 version.