---
bibliography: references.bib
csl: ../Scripts/nature.csl
---

```{=html}
<div class="subheader doc-header" style="width: 100%; margin-left: 0px; margin-right: 0px; margin-bottom: 30px">
    <div class="blob"></div>
    <div class="header-content">
        <h2>Pipeline Development Documentation</h2>
    </div>
</div>
```

<small>Last Updated: September 1<sup>st</sup>, 2026</small>

# Overview

Researchers and stakeholders interested in understanding how the project was developed may refer to the following PDF reports for further details. These reports document the characteristics of the raw data, troubleshooting strategies for algorithmic development, and interpret benchmarks and outcomes assessing algorithm performance and estimating the degree of accuracy achieved.

Note that in May 2026, an updated version of the raw data was provided in a format different from that of the version saved in July 2023 and provided in Summer 2025. As a result, data processing was divided into two paths: one for the **2023 Format** and one for the **2026 Format**.

2026 versions of comparable sections should be treated as the most current methodology applicable to ongoing research. Insights derived from the 2023 Format are assumed to apply to the 2026 Format as well. Unexpected outcomes or shortcomings in algorithm performance identified in the 2023 drafts were used to inform improvements applied in the 2026 version.

# Project Objectives

1. **REVIEW:** Evaluate the raw data and previously outlined cleaning, validation, and harmonization methods employed by [Insang Song, Ph.D.](https://sigmafelix.wixsite.com/mysite) for accuracy and identify opportunities for improvement.

2. **PREPARATION:** Implement identified improvements to prepare the dataset for analysis and distribution to qualifying collaborators.

3. **METRICS:** Calculate the metrics necessary for dynamic visualization.

Additionally, the project pipeline should be reasonably reproducible for future collaborators and readily adaptable to potential changes in project scope.

# Reports

## 2023 Format

```{=html}
<div class="download-buttons">
  <a href="Reports/Review_2023 Format.pdf" download="Review_2023 Format.pdf">
    <button class="btn"><i class="bi bi-download"></i>&nbsp Raw Data Review</button>
  </a>
  <a href="Reports/Preparation_2023 Format.pdf" download="Preparation_2023 Format.pdf">
    <button class="btn"><i class="bi bi-download"></i>&nbsp Data Preparation</button>
  </a>
  <a href="Reports/Metrics_2023 Format.pdf" download="Metrics_2023 Format.pdf">
    <button class="btn"><i class="bi bi-download"></i>&nbsp Metric Generation</button>
  </a>
</div>
```

## 2026 Format

```{=html}
<div class="download-buttons">
  <a href="Reports/Review_2026 Format.pdf" download="Review_2026 Format.pdf">
    <button class="btn"><i class="bi bi-download"></i>&nbsp Raw Data Review</button>
  </a>
  <a href="Reports/Preparation_2026 Format.pdf" download="Preparation_2026 Format.pdf">
    <button class="btn"><i class="bi bi-download"></i>&nbsp Data Preparation</button>
  </a>
  <a href="Reports/Metrics_2026 Format.pdf" download="Metrics_2026 Format.pdf">
    <button class="btn"><i class="bi bi-download"></i>&nbsp Metric Generation</button>
  </a>
</div>
```

# Important Links and Locations

In accordance with the Data Use Agreement for this dataset, some repositories may not be publicly accessible or may contain local files that are not tracked by Git and or included on GitHub. Complete copies of the data and summary results can be accessed in the `"SOCAH LAB\Church closing\Raw data"` folder on Yale's OneDrive.

Summer 2025 dashboard prototype by [Gordon Tu](https://gordontu.com/): [Closed Churches in the US](https://church-closing-dashboard.vercel.app/)

Original GitHub Repo by Dr. Song: [sigmafelix/healthreligion_project](https://github.com/sigmafelix/healthreligion_project)

Current Project GitHub Repo: [SOCAH-Lab/Church-Closures-Dashboard](https://github.com/SOCAH-Lab/Church-Closures-Dashboard)